config/routes.rb
Rails.application.routes.draw do
  namespace :site do
    get 'welcome/index'
    get 'search', to: 'search#question'
    get 'subject/:subject_id/:subject', to: 'search#subject', as: 'search_subject'
    post 'answer', to: 'answer#question'
  end

  namespace :users_backoffice do
    get 'welcome/index'
    get 'profile', to: 'profile#edit'
    patch 'profile', to: 'profile#update'
  end
  devise_for :users

  namespace :admins_backoffice do
    get 'welcome/index'
    resources :admins
    resources :subjects
    resources :questions
  end
  devise_for :admins, skip: %i[registration]

  get '/admin', to: 'admins_backoffice/welcome#index'
  root to: 'site/welcome#index'
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :subject, counter_cache: true, inverse_of: :questions
  has_many :answers, dependent: :destroy

  accepts_nested_attributes_for :answers, reject_if: :all_blank, allow_destroy: true

  # Callbacks
  after_create :set_statistic

  # Scopes
  scope :search_subject, lambda { |subject_id, page_number|
    Question.includes(:answers, :subject)
            .where(subject_id: subject_id)
            .desc_order
            .paginate(page_number)
  }

  scope :search_question, lambda { |term, page_number|
    Question.includes(:answers, :subject)
            .where('lower(description) LIKE ?', "%#{term.downcase}%")
            .desc_order
            .paginate(page_number)
  }

  scope :last_questions, lambda { |page_number|
    Question.includes(:answers, :subject)
            .desc_order
            .paginate(page_number)
  }

  scope :desc_order, -> { order(created_at: :desc) }

  scope :paginate, ->(page_number) { page(page_number) }

  # Kaminari
  paginates_per 15

  private

  def set_statistic
    AdminStatistic.assing_event(AdminStatistic::EVENTS[:total_questions])
  end
end

app/controllers/admins_backoffice/admins_controller.rb
class AdminsBackoffice::AdminsController < AdminsBackofficeController
  before_action :set_admin, only: %i[edit update destroy]
  before_action :check_password, only: %i[update]

  def index
    respond_to do |format|
      format.html { @admins = Admin.all.page(params[:page]) }
      format.pdf { @admins = Admin.all }
    end
  end

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(admin_params)

    if @admin.save
      redirect_to admins_backoffice_admins_path,
                  notice: t('notice.admin_backoffice.create', entity: t('activerecord.models.admin.one'), gender: 'o')
    else
      render :new
    end
  end

  def edit; end

  def update
    if @admin.update(admin_params)
      AdminMailer.update_email(current_admin, @admin).deliver_now
      redirect_to admins_backoffice_admins_path,
                  notice: t('notice.admin_backoffice.update', entity: t('activerecord.models.admin.one'), gender: 'o')
    else
      render :edit
    end
  end

  def destroy
    if @admin.destroy
      redirect_to admins_backoffice_admins_path,
                  notice: t('notice.admin_backoffice.delete', entity: t('activerecord.models.admin.one'), gender: 'o')
    else
      render :index
    end
  end

  private

  def set_admin
    @admin = Admin.find(params[:id])
  end

  def admin_params
    params.require(:admin).permit(:email, :password, :password_confirmation)
  end

  def check_password
    if params[:admin][:password].blank? &&
       params[:admin][:password_confirmation].blank?

      params[:admin].extract!(:password, :password_confirmation)
    end
  end
end

app/controllers/admins_backoffice/questions_controller.rb
class AdminsBackoffice::QuestionsController < AdminsBackofficeController
  before_action :set_question, only: %i[edit update destroy]
  before_action :search_all_subjects, only: %i[edit new]

  def index
    respond_to do |format|
      format.html { @questions = Question.includes(:subject).page(params[:page]) }
      format.pdf { @questions = Question.includes(:subject) }
      format.json { @questions = Question.includes(:subject, :answers) }
    end
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to admins_backoffice_questions_path,
                  notice: t('notice.admin_backoffice.create', entity: t('activerecord.models.question.one'),
                                                              gender: 'a')
    else
      render :new
    end
  end

  def edit; end

  def update
    if @question.update(question_params)
      redirect_to admins_backoffice_questions_path,
                  notice: t('notice.admin_backoffice.update', entity: t('activerecord.models.question.one'),
                                                              gender: 'a')
    else
      render :edit
    end
  end

  def destroy
    if @question.destroy
      redirect_to admins_backoffice_questions_path,
                  notice: t('notice.admin_backoffice.delete', entity: t('activerecord.models.question.one'),
                                                              gender: 'a')
    else
      render :index
    end
  end

  private

  def question_params
    params.require(:question).permit(:description, :subject_id, answers_attributes: %i[id description correct _destroy])
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def search_all_subjects
    @subjects = Subject.all
  end
end

app/controllers/admins_backoffice/subjects_controller.rb
class AdminsBackoffice::SubjectsController < AdminsBackofficeController
  before_action :set_subject, only: %i[edit update destroy]

  def index
    respond_to do |format|
      format.html { @subjects = Subject.all.page(params[:page]) }
      format.pdf { @subjects = Subject.all }
      format.json { @subjects = Subject.all }
    end
  end

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new(subject_params)

    if @subject.save
      redirect_to admins_backoffice_subjects_path,
                  notice: t('notice.admin_backoffice.create', entity: t('activerecord.models.subject.one'), gender: 'o')
    else
      render :new
    end
  end

  def edit; end

  def update
    if @subject.update(subject_params)
      redirect_to admins_backoffice_subjects_path,
                  notice: t('notice.admin_backoffice.update', entity: t('activerecord.models.subject.one'), gender: 'o')
    else
      render :edit
    end
  end

  def destroy
    if @subject.destroy
      redirect_to admins_backoffice_subjects_path,
                  notice: t('notice.admin_backoffice.delete', entity: t('activerecord.models.subject.one'), gender: 'o')
    else
      render :index
    end
  end

  private

  def subject_params
    params.require(:subject).permit(:description)
  end

  def set_subject
    @subject = Subject.find(params[:id])
  end
end

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  def index
    @total_users = AdminStatistic.total_users
    @total_questions = AdminStatistic.total_questions
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout 'admins_backoffice'
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/questions_helper.rb
module AdminsBackoffice::QuestionsHelper
end

app/helpers/admins_backoffice/subjects_helper.rb
module AdminsBackoffice::SubjectsHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
  def translate_attribute(object = nil, method = nil)
    if object && method
      object.model.human_attribute_name(method.to_sym)
    else
      'Invalid parameters to complete the translation of this attribute'
    end
  end
end

app/views/admins_backoffice/questions/_answer_fields.html.erb
<div class="nested-fields">
  <div class="form-group">
    <%= f.label :description %>
  </div>
  <div class="form-group">
    <%= f.text_field :description, class: 'form-control', placeholder: t('placeholder.answer.type_a_new_answer')%>
    <br>
    <%= f.check_box :correct %> <%= t('interactions.message.its_correct') %>
    <%= link_to_remove_association(t('interactions.link.remove'), f)  %>
  </div>
</div>

app/views/admins_backoffice/questions/edit.html.erb
<%= render partial: 'admins_backoffice/questions/shared/form', 
           locals: { action_message: t('messages.edit')} %>

app/views/admins_backoffice/questions/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"> <%= t('messages.listing', model: @questions.model_name.human(count: 2)) %> </h1>
  </div>
</div>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th> <%= translate_attribute(@questions, :id) %> </th>
        <th> <%= translate_attribute(@questions, :description) %> </th>
        <th> <%= translate_attribute(@questions, :subject) %> </th>
        <th>
          <%= link_to new_admins_backoffice_question_path, class: 'btn btn-success btn-circle' do %>
            <i class="fa fa-plus"></i>
          <%end %>

          <%= link_to admins_backoffice_questions_path(format: :pdf), class: 'btn btn-warning btn-circle' do %>
            <i class="fa fa-file-pdf-o"></i>
          <% end %>
        </th>
      </tr>
    </thead>
    <tbody>
      <% @questions.each do |question| %>
        <tr>
          <td> <%= question.id %> </td>
          <td> <%= question.description.truncate(100) %></td>
          <td> <%= question.subject.description.truncate(40) %></td>
          <td style="width: 100px;">
            <%= link_to edit_admins_backoffice_question_path(question), class:'btn btn-primary btn-circle' do %>
              <i class="fa fa-edit"></i>
            <% end %>
            <%= link_to admins_backoffice_question_path(question), 
                method: :delete, 
                class:"btn btn-danger btn-circle", 
                data: { confirm: t('messages.confirm_with', item: question.description.truncate(30)) }  do %>
              <i class="fa fa-minus"></i>
            <%end %>
          </td>
        </tr>
      <%end %>
    </tbody>
  </table>

  <div class="text-center">
    <%= paginate @questions %>
  </div>
</div>

app/views/admins_backoffice/questions/new.html.erb
<%= render partial: 'admins_backoffice/questions/shared/form', 
           locals: { action_message: t('messages.new', model: '') } %>